[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[dev]
  framework = "vite"
  targetPort = 5173       # Where Vite runs
  port = 8888             # Netlify dev runs here
  functionsPort = 9999    # Netlify's function builder runs here
  autoLaunch = true
